version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install Front-End
          command: |
            yarn run frontend:install
      - run:
          name: Install Back-End
          command: |
            yarn run backend:install
      - run:
          name: Build Front-End
          command: |
            yarn run frontend:build
      - run:
          name: Build Back-End
          command: |
            yarn run backend:build
      - run:
          name: Deploy App
          command: |
            yarn run frontend:deploy