version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - aws-cli/setup
      - run:
          name: Install Front-End
          command: |
            npm run frontend:install
      - run:
          name: Install Back-End
          command: |
            npm run backend:install
      - run:
          name: Build Front-End
          command: |
            npm run frontend:build
      - run:
          name: Build Back-End
          command: |
            npm run backend:build
      - run:
          name: Forntend App
          command: |
            npm run frontend:deploy
      - run:
          name: Backend App
          command: |
            npm run backend:deploy